language: php

php: 
    - 7.4.3
    
branches:
    only:
        - tests

before_script:
    - composer install
    - composer require --dev laravel/dusk:"^4.0"
    - php artisan dusk:install
    
script:
    - php artisan dusk
    
