language: php

php: 
    - 7.4.3
    
branches:
    only:
        - tests

services:
    - mysql
    - docker 

before_script:
    - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
    - docker-php-ext-install mysqli
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cp .env.dusk.local .env
    - composer require laravel/dusk:"^4.0"
    - composer update
    - php artisan dusk:install
    - mysql -u root -h 127.0.0.1 chat_db < chat_db.sql 
    
script:
    - php artisan dusk
    
definitions:
 services:
   mysql:
     image: mysql:5.6
     environment:
        MYSQL_DATABASE: 'chat_db'
        MYSQL_USER: 'root'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  
