language: php

php: 
    - 7.4.3
    
branches:
    only:
        - tests

services:
    - mysql
    
definitions:
 services:
   mysql:
     image: mysql:5.6
     environment:
        MYSQL_DATABASE: 'chat_db'
        MYSQL_USER: 'root'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'   

before_script:
    - cp .env.dusk.local .env
    - composer require laravel/dusk:"^4.0"
    - composer update
    - php artisan dusk:install
    - mysql -e 'create database chat_db;'
    - mysql -u root -h localhost chat_db < chat_db.sql
    
script:
    - php artisan dusk
    

