language: php

php: 
    - 7.4.3
    
branches:
    only:
        - tests

before_script:
    - rm -Rf vendor
    - composer install --no-dev
    - composer require laravel/dusk
    - composer update
    
script:
    - php artisan dusk
    
